### ISSUE TITLE
square bracket attr in selector set to undefined

### ISSUE THREAD

**Issue by CreaturesInUnitards** [dom-dee-dom/vella#11]
`v("[x]")` should emit 

`<div x="true"></div>`, 

but instead emits 

`<div x="undefined"></div>`

**Comment by leeoniya** [comment]
`v("[x]")` should probably emit `<div x></div>` or `<div x=""></div>` or `<div x="x"></div>`

html is weird.

**Comment by CreaturesInUnitards** [comment]
@leeoniya you're _so_ right — this came right out of a Mithril test case that vella failed... I was clearly on autopilot :)

In any case, it should NOT be `<div x="undefined" />`

**Comment by pygy** [comment]
Yup, I'm working on a fix (Setting it to `""` which is what HTML5 does)
