### ISSUE TITLE
classes in attrs are obliterating classes in selector

### ISSUE THREAD

**Issue by CreaturesInUnitards** [dom-dee-dom/vella#12]
`v(".foo.bar", { class: "gronk" })`

should emit

`<div class="foo bar gronk"></div>`

but instead emits

`<div class="gronk"></div>`

**Comment by pygy** [comment]
Yup, I'm going to use `classList.add`/`.remove` for non-selector attrs so that we can set and remove classes independently (as long as the sets of dynamic classes are disjoint).
