### ISSUE TITLE
Components should be live zones

### ISSUE THREAD

**Issue by barneycarroll** [dom-dee-dom/vella#20]
Live zones, aka functions as hyperscript nodes, are 'reactivity barriers'. Reactivity barriers complicate the data / view intersection as it mandates that any upstream data dependencies settle before the view subtrees internal computations can be resolved. Without this requirement, the data and view layers would produce more or less independent execution graphs whose operations can be sequenced and batched according to relatively simple logic; with this requirement, each computation taking place _in the view_ which produces view code containing its own computations must essentially create new subsidiary data and view execution graphs, reducing opportunities for holistic data computation efficiency. Thus there is a priori an incentive to avoid live zones where possible - they de-optimise the application code path.

Components are currently not live zones: any interpolations made inside them will not be mapped into the data dependency graph. This is a footgun allowing for stale data islands, and is counter-intuitive since all other functions received and executed by Vellas hyperscript are implicitly to be computed as part of the data dependency graph. It is trivially possible for a component to immediately invoke a live zone, but the assumption is that a component does not contain logic pertinent to the data layer.

```js
const comp1 = () => {
  // won't recompute
  const x = y() * z()

  // Fixed at initial value
  return x
}

const comp1 = () => () => {  // < live zone
  // will recompute whenever x or y update
  const x = y() * z()

  // Updates accordingly
  return x
} 
```

This reminds me of Mithrils route endpoint entities: the user is asked to make a high level choice between orthogonal behaviours as if there is a logical mutual exclusivity, which in application authoring terms may not be apparent *.

Presenting authors with a choice between logical encapsulation concerns and performance concerns is to my mind an obnoxious dilemma which trades framework responsibility for user neurosis. Effectively we are with one hand vaunting the value proposition that complex data dependency concerns can be determined and optimised for procedurally, but then with the other telling authors they should be perpetually concerned with whether these powerful tools are really necessary: it's "don't make me think" followed by "think long and hard".

\* Either the route runs execution logic on each match _or_ it asynchronously resolves to a component _or_ it has a teardown.

**Comment by pygy** [comment]
The model is a bit different: what happens inside a component belongs to the parent live zone, unless wrapped in a computation. So your first example

```JS
const Product = ({y,z}) => {
  const x = y() * z()
  console.log("product")
  // Fixed at initial value
  return x
}
const y = v.data(1)
const z = v.data(2)
boot(document.body, () => (console.log("drawn"), v(Product, {y, z})))
setInterval(()=>{ x(x()+1); y(y()*2) }, 500)
```
Will log `"drawn",  "product"` on every x/y update.

Even if component became reactivity barriers, you'd still get `"product"` logged.

In the first case the DOM of the root (the parent live zone) would be redrawn if there was any beside the product. In the second case, only the content of `Product` would be.

You need to define `x` as a live zone or as a stream for the redraws to become completely granular, hence the need for #18 to make our lives easier.

**Comment by barneycarroll** [comment]
Seeing as it's trivial for a computation to introduce a live zone, I think my issue doesn't make much sense. But the answer was helpful in explaining the ramifications of live zones!
