### ISSUE TITLE
Should attributes defined in the selector considered defaults to be restored if a dynamic attr is removed?

### ISSUE THREAD

**Issue by pygy** [dom-dee-dom/vella#23]
Suppose `v("[a=b]", {a: () c() ? "c" : null})`. 

When `c() === false` should `a` be `"b"`, or unset? Mithril says "unset".

**Comment by pygy** [comment]
Note that the "default" semantics is already implemented for classes (you can't delete a class set by the selector string).

**Comment by barneycarroll** [comment]
No, I would expect attributes to behave as overrides

**Comment by foxdonut** [comment]
Classes are different since they are a list.

I too would expect attributes to have precedence.

We would document this behaviour as ("what would happen if..."), but in practice, you would either define an attribute in the selector or in the attributes, never both.

**Comment by pygy** [comment]
"unset" is the easy way too, implementation-wise. Let's do that.
